### ISSUE TITLE
LoadResource fails on python 3.5 and python 3.6 (64bits)

### ISSUE THREAD

**Issue by itziakos** [enthought/pywin32-ctypes#51]
```python

======================================================================
ERROR: test_load_resource (win32ctypes.tests.test_win32api.TestWin32API)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\projects\pywin32-ctypes\build\lib\win32ctypes\tests\test_win32api.py", line 112, in test_load_resource
    resource_language)
  File "c:\projects\pywin32-ctypes\build\lib\win32ctypes\pywin32\win32api.py", line 189, in LoadResource
    return _common._PyBytes_FromStringAndSize(pointer, size)
ctypes.ArgumentError: argument 1: <class 'OverflowError'>: int too long to convert

----------------------------------------------------------------------
Ran 14 tests in 12.146s
```

**Comment by itziakos** [comment]
fixed by #52
