### ISSUE TITLE
Issue pip installing v0.1.0 from pypi

### ISSUE THREAD

**Issue by andscho-msft** [enthought/pywin32-ctypes#61]
Hello,

Since the 0.1.0 wheel was published to pypi, I have been getting this error when trying to pip install on Windows.

It appears that the VERSION file is not being included in the package?

``` 
Collecting pywin32-ctypes; sys_platform == "win32" (from keyring>=5.6->msrestazure~=0.4.7->azure-keyvault==0.2.0->-r M:\GeneralVS15-055\_work\21\s\myrepo\requirements.txt (line 2))
   Using cached pywin32-ctypes-0.1.0.tar.gz
     Complete output from command python setup.py egg_info:
     Traceback (most recent call last):
       File "<string>", line 1, in <module>
       File "M:\GeneralVS15-055\_work\_temp\pip-build-uwujm7ug\pywin32-ctypes\setup.py", line 7, in <module>
         os.path.join(HERE, 'VERSION')).read().strip()
     FileNotFoundError: [Errno 2] No such file or directory: 'M:\\GeneralVS15-055\\_work\\_temp\\pip-build-uwujm7ug\\pywin32-ctypes\\VERSION'
     
     ----------------------------------------
 ##[error]Command "python setup.py egg_info" failed with error code 1 in M:\GeneralVS15-055\_work\_temp\pip-build-uwujm7ug\pywin32-ctypes\

 ##[error]Process completed with exit code 1 and had 1 error(s) written to the error stream.
```
Thanks,
Andrew

### Workaround
Just add this line to your requirements.txt
```
pywin32-ctypes == 0.0.1
```

**Comment by andscho-msft** [comment]
Appears to be dupe of https://github.com/enthought/pywin32-ctypes/issues/60, sorry

**Comment by silvana-i** [comment]
I did have "janky" formatting in there :) and my version was wrong. I fixed it now. Thanks for pointing it out.

**Comment by andscho-msft** [comment]
Ok closing as Dupe of #60
